<<<<<<< HEAD
version: 2

sources:
  - name: raw
    database: dbt-project-486407
    schema: raw
    tables:
      - name: customers
      - name: products
      - name: orders
      - name: order_items
